version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - performance
        - style
  exclusions:
    rules:
      - path: "main.go"
        linters:
          - all

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

run:
  timeout: 5m