FROM golang:1.24-bullseye

RUN apt update && apt install -y --fix-missing \
    libgtk-3-dev \
    libwebkit2gtk-4.0-dev \
    nodejs npm \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/wailsapp/wails/v2/cmd/wails@latest

RUN npm install -g pnpm


ENV PATH=$PATH:/go/bin

WORKDIR /app

COPY .. .

RUN pnpm install

RUN wails build
