// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {projects} from '../models';
import {sshconn} from '../models';
import {workspaces} from '../models';
import {context} from '../models';
import {vault} from '../models';

export function CloseSSHTerminal(arg1:string):Promise<types.APIResponse_map_string_string_>;

export function ConnectSSHConnection(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionState_>;

export function CreateProject(arg1:projects.CreateProjectRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_projects_ProjectDTO_>;

export function CreateSSHConnection(arg1:sshconn.CreateConnectionRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionDTO_>;

export function CreateWorkspace(arg1:workspaces.CreateWorkspaceRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_workspaces_WorkspaceDTO_>;

export function DeleteProject(arg1:string):Promise<types.APIResponse_map_string_string_>;

export function DeleteProjectIcon(arg1:string):Promise<types.APIResponse_map_string_string_>;

export function DeleteSSHConnection(arg1:string):Promise<types.APIResponse_map_string_string_>;

export function DeleteWorkspace(arg1:string):Promise<types.APIResponse_map_string_string_>;

export function DisconnectSSHConnection(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionState_>;

export function GetAuthState():Promise<types.APIResponse_map_string_string_>;

export function GetHomeDirectory():Promise<types.APIResponse_string_>;

export function GetProject(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_projects_ProjectDTO_>;

export function GetProjectIcon(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_projects_ProjectIconDTO_>;

export function GetSSHConnection(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionDTO_>;

export function GetSettings():Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_settings_Settings_>;

export function GetVaultState():Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_vault_VaultState_>;

export function GetWorkspace(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_workspaces_WorkspaceDTO_>;

export function ListConnectedSSH():Promise<types.APIResponse___string_>;

export function ListDirectory(arg1:string):Promise<types.APIResponse___github_com_Velarvo_velarvo_desktop_internal_app_ExplorerNode_>;

export function ListProjects():Promise<types.APIResponse___github_com_Velarvo_velarvo_desktop_internal_projects_ProjectDTO_>;

export function ListSSHConnections(arg1:string):Promise<types.APIResponse___github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionDTO_>;

export function ListWorkspaces(arg1:string):Promise<types.APIResponse___github_com_Velarvo_velarvo_desktop_internal_workspaces_WorkspaceDTO_>;

export function LockVault():Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_vault_VaultState_>;

export function Login(arg1:string,arg2:string):Promise<types.APIResponse_map_string_string_>;

export function Logout():Promise<types.APIResponse_map_string_string_>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OpenSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<types.APIResponse_string_>;

export function Refresh():Promise<types.APIResponse_map_string_string_>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<types.APIResponse_map_string_string_>;

export function ResizeSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<types.APIResponse_map_string_string_>;

export function SetProjectIcon(arg1:projects.SetProjectIconRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_projects_ProjectIconDTO_>;

export function SetUILanguage(arg1:string):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_settings_Settings_>;

export function SetupVault(arg1:vault.SetupRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_vault_VaultState_>;

export function Startup(arg1:context.Context):Promise<void>;

export function UnlockVault(arg1:vault.UnlockRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_vault_VaultState_>;

export function UpdateProject(arg1:projects.UpdateProjectRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_projects_ProjectDTO_>;

export function UpdateSSHConnection(arg1:sshconn.UpdateConnectionRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_sshconn_ConnectionDTO_>;

export function UpdateWorkspace(arg1:workspaces.UpdateWorkspaceRequest):Promise<types.APIResponse_github_com_Velarvo_velarvo_desktop_internal_workspaces_WorkspaceDTO_>;

export function WriteSSHTerminal(arg1:string,arg2:string):Promise<types.APIResponse_map_string_string_>;
