// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSSHTerminal(arg1) {
  return window['go']['app']['App']['CloseSSHTerminal'](arg1);
}

export function ConnectSSHConnection(arg1) {
  return window['go']['app']['App']['ConnectSSHConnection'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function CreateSSHConnection(arg1) {
  return window['go']['app']['App']['CreateSSHConnection'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['app']['App']['CreateWorkspace'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteProjectIcon(arg1) {
  return window['go']['app']['App']['DeleteProjectIcon'](arg1);
}

export function DeleteSSHConnection(arg1) {
  return window['go']['app']['App']['DeleteSSHConnection'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['App']['DeleteWorkspace'](arg1);
}

export function DisconnectSSHConnection(arg1) {
  return window['go']['app']['App']['DisconnectSSHConnection'](arg1);
}

export function GetAuthState() {
  return window['go']['app']['App']['GetAuthState']();
}

export function GetHomeDirectory() {
  return window['go']['app']['App']['GetHomeDirectory']();
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjectIcon(arg1) {
  return window['go']['app']['App']['GetProjectIcon'](arg1);
}

export function GetSSHConnection(arg1) {
  return window['go']['app']['App']['GetSSHConnection'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVaultState() {
  return window['go']['app']['App']['GetVaultState']();
}

export function GetWorkspace(arg1) {
  return window['go']['app']['App']['GetWorkspace'](arg1);
}

export function ListConnectedSSH() {
  return window['go']['app']['App']['ListConnectedSSH']();
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListSSHConnections(arg1) {
  return window['go']['app']['App']['ListSSHConnections'](arg1);
}

export function ListWorkspaces(arg1) {
  return window['go']['app']['App']['ListWorkspaces'](arg1);
}

export function LockVault() {
  return window['go']['app']['App']['LockVault']();
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function OnBeforeClose(arg1) {
  return window['go']['app']['App']['OnBeforeClose'](arg1);
}

export function OnDomReady(arg1) {
  return window['go']['app']['App']['OnDomReady'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['app']['App']['OnShutdown'](arg1);
}

export function OpenSSHTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenSSHTerminal'](arg1, arg2, arg3);
}

export function Refresh() {
  return window['go']['app']['App']['Refresh']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function ResizeSSHTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeSSHTerminal'](arg1, arg2, arg3);
}

export function SetProjectIcon(arg1) {
  return window['go']['app']['App']['SetProjectIcon'](arg1);
}

export function SetUILanguage(arg1) {
  return window['go']['app']['App']['SetUILanguage'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['app']['App']['SetupVault'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['app']['App']['UnlockVault'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['app']['App']['UpdateProject'](arg1);
}

export function UpdateSSHConnection(arg1) {
  return window['go']['app']['App']['UpdateSSHConnection'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['app']['App']['UpdateWorkspace'](arg1);
}

export function WriteSSHTerminal(arg1, arg2) {
  return window['go']['app']['App']['WriteSSHTerminal'](arg1, arg2);
}
